<?php
/**
 * Plugin Name: Scrollies
 * Description: Enlive your webpage with scrolling sheeps, catch visitor's eye.
 * Version: 1.0.1
 * Requires at least: 4.5
 * Author: Roman Flössler
 * Author URI: https://github.com/Roman-Flossler
 * License: GPL-3.0
 * License URI: http://www.gnu.org/licenses/gpl-3.0.html
 */


defined( 'ABSPATH' ) or die( 'Only for Wordpress' );
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class Scrollies {
	private $scrollies_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'scrollies_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'scrollies_page_init' ) );
	}

	public function scrollies_add_plugin_page() {
		add_options_page(
			'Scrollies', // page_title
			'Scrollies', // menu_title
			'manage_options', // capability
			'scrollies', // menu_slug
			array( $this, 'scrollies_create_admin_page' ) // function
		);


		$this->default_options = array(
			"sheep_1_position" => "81",
			"sheep_2_position" => "72",
			"sheep_3_position" => "33",
			"z_index" => "auto",
			"sheep_color" => "#cacaca",
			"sheep_shadow_color" => "none"
		);		
	}		


	public function scrollies_create_admin_page() {		
		$this->scrollies_options = get_option( 'scrollies_option_array',  $this->default_options ); ?>

		<div class="wrap">
			<h2>Scrollies</h2>
			<p>In this moment, there is only one type of scrollies - sheeps<br>
			If sheeps won't appear, set high enough <strong>z-index</strong> number.
			</p>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'scrollies_option_group' );
					do_settings_sections( 'scrollies-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function scrollies_page_init() {
		register_setting(
			'scrollies_option_group', // option_group
			'scrollies_option_array', // option_name
			array( $this, 'scrollies_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'scrollies_setting_section', // id
			'Settings', // title
			array( $this, 'scrollies_section_info' ), // callback
			'scrollies-admin' // page
		);

		add_settings_field(
			'sheep_1_position', // id
			'Sheep1 ewe position', // title
			array( $this, 'sheep_1_position_callback' ), // callback
			'scrollies-admin', // page
			'scrollies_setting_section' // section
		);

		add_settings_field(
			'sheep_2_position', // id
			'Sheep2 ewe position', // title
			array( $this, 'sheep_2_position_callback' ), // callback
			'scrollies-admin', // page
			'scrollies_setting_section' // section
		);

		add_settings_field(
			'sheep_3_position', // id
			'Sheep3 ram position', // title
			array( $this, 'sheep_3_position_callback' ), // callback
			'scrollies-admin', // page
			'scrollies_setting_section' // section
		);

		add_settings_field(
			'z_index', // id
			'Sheeps z-index', // title
			array( $this, 'z_index_callback' ), // callback
			'scrollies-admin', // page
			'scrollies_setting_section' // section
		);

		add_settings_field(
			'sheep_color', // id
			'Sheeps color', // title
			array( $this, 'sheep_color_callback' ), // callback
			'scrollies-admin', // page
			'scrollies_setting_section' // section
		);

		add_settings_field(
			'sheep_shadow_color', // id
			'Sheeps shadow color', // title
			array( $this, 'sheep_shadow_color_callback' ), // callback
			'scrollies-admin', // page
			'scrollies_setting_section' // section
		);
	}

	public function scrollies_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['sheep_1_position'] ) ) {
			$sanitary_values['sheep_1_position'] = sanitize_text_field( $input['sheep_1_position'] );
		}

		if ( isset( $input['sheep_2_position'] ) ) {
			$sanitary_values['sheep_2_position'] = sanitize_text_field( $input['sheep_2_position'] );
		}

		if ( isset( $input['sheep_3_position'] ) ) {
			$sanitary_values['sheep_3_position'] = sanitize_text_field( $input['sheep_3_position'] );
		}

		if ( isset( $input['z_index'] ) ) {
			$sanitary_values['z_index'] = sanitize_text_field( $input['z_index'] );
		}

		if ( isset( $input['sheep_color'] ) ) {
			$sanitary_values['sheep_color'] = sanitize_text_field( $input['sheep_color'] );
		}

		if ( isset( $input['sheep_shadow_color'] ) ) {
			$sanitary_values['sheep_shadow_color'] = sanitize_text_field( $input['sheep_shadow_color'] );
		}

		return $sanitary_values;
	}

	public function scrollies_section_info() {
		echo "Position of a scrolly (sheep) is given by number from 0 (screen top) to 100 (screen bottom). <br> If you don't want some sheep to display just use some text e.g. goaway";
	}

	public function sheep_1_position_callback() {
		printf(
			'<input class="regular-text" type="text" name="scrollies_option_array[sheep_1_position]" id="sheep_1_position" value="%s" style="width: 21em; margin-right: 1em;">',
			isset( $this->scrollies_options['sheep_1_position'] ) ? esc_attr( $this->scrollies_options['sheep_1_position']) : ''
		);
	}

	public function sheep_2_position_callback() {
		printf(
			'<input class="regular-text" type="text" name="scrollies_option_array[sheep_2_position]" id="sheep_2_position" value="%s" style="width: 21em; margin-right: 1em;">',
			isset( $this->scrollies_options['sheep_2_position'] ) ? esc_attr( $this->scrollies_options['sheep_2_position']) : ''
		);
	}

	public function sheep_3_position_callback() {
		printf(
			'<input class="regular-text" type="text" name="scrollies_option_array[sheep_3_position]" id="sheep_3_position" value="%s" style="width: 21em; margin-right: 1em;">',
			isset( $this->scrollies_options['sheep_3_position'] ) ? esc_attr( $this->scrollies_options['sheep_3_position']) : ''
		);
	}

	public function z_index_callback() {
		printf(
			'<input class="regular-text" type="text" name="scrollies_option_array[z_index]" id="z_index" value="%s" style="width: 21em;margin-right: 1em;"><br>
			<label for="z_index">If sheeps are hidden behind a sidebar or header, set high enough z-index to bring them to front. <br> You can try random numbers ( 10, 100, 1000, 10000, … ), until it will work.</label>',
			isset( $this->scrollies_options['z_index'] ) ? esc_attr( $this->scrollies_options['z_index']) : ''
		);
	}

	public function sheep_color_callback() {
		printf(
			'<input class="regular-text" type="text" name="scrollies_option_array[sheep_color]" id="sheep_color" value="%s" style="width: 21em; margin-right: 1em;"><br>
			<label for="sheep_color">color in CSS format e.g. #cacaca, blue, rgb(38, 133, 29)</label>',
			isset( $this->scrollies_options['sheep_color'] ) ? esc_attr( $this->scrollies_options['sheep_color']) : ''
		);
	}

	public function sheep_shadow_color_callback() {
		printf(
			'<input class="regular-text" type="text" name="scrollies_option_array[sheep_shadow_color]" id="sheep_shadow_color" value="%s" style="width: 21em; margin-right: 1em;"><br>
			<label for="sheep_color">color in CSS format e.g. #cacaca, blue, rgb(38, 133, 29) or none color</label>',
			isset( $this->scrollies_options['sheep_shadow_color'] ) ? esc_attr( $this->scrollies_options['sheep_shadow_color']) : ''
		);
	}

}

if ( is_admin() )
	$scrollies = new Scrollies();

/* Add settings link to plugin page  */

add_filter( 'plugin_action_links_'.plugin_basename(__FILE__), 'scrollies_add_settings_link' );
function scrollies_add_settings_link( $links ) {
	$links[] = '<a href="' .
		admin_url( 'options-general.php?page=scrollies' ) .
		'">' . __( 'Settings' ) . '</a>';
	return $links;
} 


/* Generate sheeps code  */

function scrollies_generate_sheeps() { 
	
	function getSheep($id, $top, $color, $shadowColor, $z_index) {
		$frame = '<div id="sheep'.$id.'" class="scrollies" style="top: '.$top.'vh; color: '.$color.'; z-index: '.$z_index.'; filter: drop-shadow(0px 0px 16px '.$shadowColor.');">';
		$legColor = 'style="background: '.$color.'"';
		$legs = '<div class="leg rear-first" '.$legColor.' ></div><div class="leg rear-second" '.$legColor.'></div><div class="leg front-first" '.$legColor.'></div><div class="leg front-second" '.$legColor.'></div>';		
		$svgsheep = '<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="451.6px" height="451.6px" viewBox="0 0 451.6 451.6" xml:space="preserve" ><g id="sheepshape" fill="currentColor"><path d="M360.3,192.3c-3-21-12-30.5-28-44.5c31.5-55-32.5-89.5-63-90C250,37.5,204,37.1,189.4,39.5c-6,1-22.5,6.5-24.8,12.5c-3.1,8.1,7.4,17,16.4,11c-8.5,6.3-11,13-13.2,18.3c-34.2-2.6-54,30.5-47.6,53c-2.3,2.6-4.8,5.2-7.3,8c-15.8,19.8-16.1,48.5-1,68.8c-4.9,13.4-4.6,28.7,0.5,41.9c4.9,12.5,14.7,19.5,22.9,29.5c-1.4,25.6,5,56.8,61.9,63.4c-14,20-22.8,53.4-13.6,72.3c10.4,21.1,40.7,21.4,60.7,17.6c38.6-7.4,101.7-67.2,87-96.8c37.6-43.6,35-71.3,8-98.7C354.8,229,361.3,218.3,360.3,192.3z M338.6,278.6c-2.7,15-1.2,17.9-10.8,32.2c-9.2,7.5-34.7,19.1-43,20.5c2,5,21.4,15.8,21.5,21.5c0.6,20.9-10.9,36.7-25.8,47.2c-17,12.1-38.3,20.2-59.4,18.4c-7.3-0.6-19.2-1.7-21.6-10.2c-3-10.1-0.2-21.5,3.1-31.1c4.6-13.4,13.8-30.6,20.1-43.1l1.1-1.7l-2-0.5c-47,4-71-26.3-62.5-49.3l3.1-8.3l-7.1-10.9c-23.8-8.2-36.5-27.6-26.1-50.3l2.5-5.2l-3.9-4.2c-17.4-18.9-15.2-49.4,7.8-60.7l5.2-2.6l-0.5-5.8c6-24.8,11.3-26.9,30-34.9l13.3-3.3L185,80c30-49,76.3-1.2,76.3-1.2c39.3-9.8,76.8,33.7,54.4,67.1l-4.6,6.7l6.5,4.9c25.8,19.6,34,51.8,3.7,73.1l-9.7,7l8,7.3C331.6,255.3,337.1,263.1,338.6,278.6z"/><circle cx="274.8" cy="367.6" r="12.3"/><path d="M308.5,339.4c4.1-17.5-19.8-47.2-38.7-28.8c0.1-0.3-10.2,10.8,0.7,16.7S306,341.4,308.5,339.4z"/><path d="M194.3,175c7.5-6.5,17.5-9,33.7-9.7c7.1,0.3,7.8-1.8,1.5-4.5c-20.6-7.3-31.4-6.2-44.5,3.1c-16.7,11.7-19.2,35.3-8.9,53.6c1.9,2.5,7.3,7.4,7.6,0.6C179,202.2,179.3,185.6,194.3,175z"/><path d="M270.8,143.3c3.8,12,4.5,23,0.5,35c-2.4,6.7-0.7,8,3.8,2.8c9.4-14.8,15.3-28.1,10.4-43.3c-6.2-19.4-30.2-31.4-48.5-24.5c-2.9,1.1-9.1,4.7-2.9,7.1C250.7,120.7,265.3,125.8,270.8,143.3z"/><path d="M235.8,266.8c-11.5-5.6-15.4-17.6-19.7-26.7c-1.2-5.6-3.4-3.1-4.3,2.4c-0.4,14.3,6.4,33.5,18.4,38c15.8,6.1,28.3,1.5,40.7-8.5c1.7-2.1,4.5-7.4-1.1-6.2C257.6,273.1,247.3,272.4,235.8,266.8z"/></g></svg>';
		$svgram = '<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="451.6px" height="451.6px" viewBox="0 0 451.6 451.6" xml:space="preserve"><g id="ramshape" fill="currentColor"><path d="M353.3,177.3c-3.4-7.2-9.4-18.2-21-29.5c16-54.8-32.5-89.5-63-90C250,37.5,204,37.1,189.4,39.5c-6,1-22.5,6.5-24.8,12.5c-3.1,8.1,7.4,17,16.4,11c-8.5,6.3-11,13-13.2,18.3c-34.2-2.6-54,30.5-47.6,53c-2.3,2.6-4.8,5.2-7.3,8c-15.8,19.8-16.1,48.5-1,68.8c-4.9,13.4-4.6,28.7,0.5,41.9c4.9,12.5,14.7,19.5,22.9,29.5c-1.4,25.6,5,56.8,61.9,63.4c-14,20-22.8,53.4-13.6,72.3c10.4,21.1,40.7,21.4,60.7,17.6c42.7-6.2,111-68,83.5-98c47.2-40.2,49.2-75.5,17.8-102.5C361.1,224,359.6,190.6,353.3,177.3z M345.6,275.3c-2.7,15-4.3,22.3-17.8,35.5c-9.2,7.5-34.7,19.1-43,20.5c2,5,21.4,15.8,21.5,21.5c0.6,20.9-10.9,36.7-25.8,47.2c-17,12.1-38.3,20.2-59.4,18.4c-7.3-0.6-19.2-1.7-21.6-10.2c-3-10.1-0.2-21.5,3.1-31.1c4.6-13.4,13.8-30.6,20.1-43.1l1.1-1.7l-2-0.5c-47,4-71-26.3-62.5-49.3l4-15.5l-8-3.7c-27.5-8-35.5-33-19.1-52.6l2.5-5.2l-3.9-4.2c-22-10.5-22.2-47.1,0.8-58.4l5.2-2.6l-0.5-5.8c6-24.8,11.3-26.9,30-34.9l13.3-3.3L185,80c30-49,76.3-1.2,76.3-1.2c33-11.8,67.7,28.2,54.4,67.1l-4.6,6.7l6.5,4.9c20,16.8,34,44.1,11.7,71l-10.7,9.5l9.6,5.8C340.9,251.4,344.1,259.8,345.6,275.3z"/><circle cx="270.8" cy="370.1" r="12.3"/><path d="M283,318.5c-20,14.5-1.4,41.7,17.7,25.8c0,0.1,8.7-7.4,12.4-13c6.5-9.8,5.1-10.8,6.8-17c6.4-22.3-0.2-47.7-18.6-62.4c-17.7-14.1-44.1-14.5-61.3,0.9c-15.7,14.2-20.1,39.7-1.9,54.9c10.3,6.5,16.3,6.4,25.7,2.8c6.5-2.5,19.4-15.9,13.8-20.3c-3.3-2.6-6.2,3.3-8.5,4.9c-3.6,2.4-9.4,4.8-13.7,4.6c-10.8-1.9-12.5-9.5-12.6-16.7c0.8-21.8,26.5-28.2,41.8-16C300.4,279.7,299,306.8,283,318.5z"/><path d="M263,144.6c5.7,12,2.2,30.4-2.5,42c16.4-10.4,24.4-36.4,15.8-54.3c-9.3-19.4-31-30-49.5-25c-14.1,3.8-24.9,25.8-27.5,28C229.8,111.3,254.6,127.1,263,144.6z"/><path d="M185.1,188.8c9.8-8.9,29.2-11.6,41.7-10.4c-14.7-12.7-36.9-12.8-51.6,0.6c-16,14.4-17.2,39.1-2.8,55.1c2.3,2.6,4.9,4.7,7.7,6.5C173.2,223.4,170.8,201.8,185.1,188.8z"/></g></svg>';
		if ($id == 3) {
			$finalCode = ($frame.$legs.$svgram.'</div>');
		} else {
			$finalCode = ($frame.$legs.$svgsheep.'</div>');
		}
		return $finalCode;
	}

	$default_options = array(
		"sheep_1_position" => "81",
		"sheep_2_position" => "72",
		"sheep_3_position" => "33",
		"z_index" => "auto",
		"sheep_color" => "#cacaca",
		"sheep_shadow_color" => "none"
	);

	$so = get_option( 'scrollies_option_array',  $default_options );


	$sheep1 = getSheep(1, $so["sheep_1_position"], $so["sheep_color"], $so["sheep_shadow_color"], $so["z_index"]);
	$sheep2 = getSheep(2, $so["sheep_2_position"], $so["sheep_color"], $so["sheep_shadow_color"], $so["z_index"]);
	$sheep3 = getSheep(3, $so["sheep_3_position"], $so["sheep_color"], $so["sheep_shadow_color"], $so["z_index"]);
	$append = "jQuery( 'body' ).append( '".$sheep1.$sheep2.$sheep3."' );";	
	$events = "window.addEventListener( 'scroll', scrollies.runAnimation ); jQuery('.scrollies').on('click mouseover', scrollies.runaway); jQuery('.scrollies').on('mouseout', scrollies.stopRunning );";
	return $append."\n".$events;
}

/* Adding CSS and JS code  */

add_action( 'wp_enqueue_scripts', 'scrollies_add_code' );

function scrollies_add_code() {
	$scrollies_url = plugin_dir_url( __FILE__ );
	wp_enqueue_style( 'scrollies-style', $scrollies_url.'scrollies-code/scrollies.min.css', array(), null, 'screen' );
	wp_enqueue_script( 'scrollies-script', $scrollies_url.'scrollies-code/scrollies.min.js', array( 'jquery' ), null, true );
	wp_add_inline_script( 'scrollies-script', scrollies_generate_sheeps(), 'after' );
}
